Add multiselection parameter to dropdown options
kbase/narrative_method_store pull request #77
Opened 2020-09-18 19:07 UTC by ialarmedalien

Adding a "multiselection" parameter to allow dropdowns to have multi select enabled. The dynamic dropdown type already has a multi selection param so I used the same format for the dropdown type.

2020-09-18 19:09 UTC, ialarmedalien commented on src/us/kbase/narrativemethodstore/db/test/NarrativeMethodDataTest.java
> +    }
git is dumb and doesn't realise that I inserted this code block and didn't change the next two tests.

2020-09-22 22:38 UTC, briehl requested changes
Mostly, I think some updated docs are needed. Otherwise, it looks great to me.

2020-09-22 23:40 UTC, ialarmedalien commented on NarrativeMethodStore.spec
> +        boolean multiselection;
OK, done!

2020-09-23 19:30 UTC, briehl commented on NarrativeMethodStore.spec
> +        boolean multiselection;
Great!

2020-09-23 19:31 UTC, briehl approved these changes

2020-09-23 21:17 UTC, merged